config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :articles , only: [:index, :new, :create, :show, :update, :edit, :destroy]
  resources :avatars, only: [:new, :create, :show, :update, :edit, :destroy]
  resources :teams, only: [:index]
  resources :categories
  get    '/mentions'      => 'pages#mentions'
  get    '/home'      => 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :category
  validates :nom, :prenom, :img_url, :bio_url, :role, :category_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :avatars
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
   @article =  Article.order(id: :desc)

  end

  def new
    @article = Article.new # needed to instantiate the form_for
  end

  def create
    @article = Article.new(article_params)
    if @article.save!
    redirect_to articles_path(@article)
    end

    # Will raise ActiveModel::ForbiddenAttributesError
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    # no need for app/views/restaurants/update.html.erb
    redirect_to article_path(@article)
  end
  def show
    @article = Article.find(params[:id])
 end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :sous_titre, :lieu, :date, :image_url, :content, :image_url_2, :content_2, :image_url_3, :content_3, :image_url_4, :content_4, :image_url_5, :content_5, :image_url_6, :image_url_7, :image_url_8, :image_url_9, :image_url_10, :legend, :legend_1, :legend_2, :legend_3, :legend_4, :legend_5, :legend_6, :legend_7, :legend_8, :legend_9, :legend_10, :video)
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def index
    @avatars = Avatar.all
  end

  def new
    @avatar = Avatar.new
  end

  def create
    @avatar = Avatar.new(avatar_params)
    if @avatar.save!
    redirect_to teams_path
    end
  end

  def edit
    @avatar = Avatar.find(params[:id])
  end

  def update
    @avatar = Avatar.find(params[:id])
    @avatar.update(avatar_params)
    redirect_to teams_path
  end

  def destroy
    @avatar = Avatar.find(params[:id])
    @avatar.destroy
    redirect_to teams_path
  end

  private

  def avatar_params
    params.require(:avatar).permit(:nom, :prenom, :img_url, :bio_url, :role, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.save!
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    redirect_to category_path(@category)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to teams_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/articles/edit.html.erb
<div class="container-ok">
  <div class="d-flex container justify-content-center display-bubble">



    <%= simple_form_for(@article) do |f| %>
         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
           <h3 class="title-new">Modifier un article</h3>
          <p class="conseil">Essayez de répartir le texte sur les différents champs intitulés "content" pour plus d'harmonie.</p>
           <%= f.input :title %>
           <%= f.input :sous_titre %>
           <%= f.input :date %>
           <%= f.input :lieu %>
           <%= f.input :video %>
           <%= f.input :image_url %>
           <%= f.input :legend %>
           <%= f.input :content %>
           <%= f.input :image_url_2 %>
           <%= f.input :legend_2 %>
           <%= f.input :content_2 %>
           <%= f.input :image_url_3 %>
           <%= f.input :legend_3 %>
           <%= f.input :content_3 %>
           <%= f.input :image_url_4 %>
           <%= f.input :legend_4 %>
           <%= f.input :content_4 %>
           <%= f.input :image_url_5 %>
           <%= f.input :legend_5 %>
           <%= f.input :content_5 %>
           <%= f.input :image_url_6 %>
           <%= f.input :legend_6 %>
           <%= f.input :image_url_7 %>
           <%= f.input :legend_7 %>
           <%= f.input :image_url_8 %>
           <%= f.input :legend_8 %>
           <%= f.input :image_url_9 %>
           <%= f.input :legend_9 %>
           <%= f.input :image_url_10 %>
           <%= f.input :legend_10 %>
         </div>

         <div class="form-actions">
           <%= f.submit "Save changes", class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>
</div>

app/views/articles/index.html.erb
<div class="container-ok">
<%= render "components/header" %>

<!--Carousel Wrapper-->
<div class="img-back-blanc"><%= link_to(image_tag("back.png", alt: "QQ29 - all rights reserved."), root_path) %></div>
<div id="carousel-example-1z" class="carousel slide carousel-fade carousel-bottom" data-ride="carousel">

  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->
  <!--Slides-->
  <div class="carousel-inner" role="listbox">

    <!--First slide-->

    <div class="carousel-item active ">

      <div><div class="overlay"></div></div>
      <img class="d-block w-100 img-diapo" src="https://res.cloudinary.com/dhvdnppdx/image/upload/v1631347582/Grille_dnpg2y.jpg"
        alt="First slide">
        <div class=" card-trip-infos-deux">

        <h2>Des aires</h2>
        <h3>RPZ</h3>
        <h3>24 Septembre - 26 Septembre 2021</h3>
        <p><i>Exposition</i></p>


      </div>
    </div>
    <!--/First slide-->
    <!--Second slide-->

  </div>
  <!--/.Slides-->
  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>

<% if user_signed_in? %>
<div class="flex-admin-deux"><%= link_to "Ajouter un article", new_article_path %></div>
<% end %>

<div class="display-grid-card">
  <% @article.each do |article| %>
    <div class="card-trip">
      <% if user_signed_in? %>
        <div class ="flex-admin">
          <%= link_to 'Supprimer', article_path(article),
            method: :delete,
            data: { confirm: 'Êtes-vous certain de vouloir supprimer?' } %>
          <%= link_to "Editer", edit_article_path(article.id)%>
        </div>
      <% end %>
          <%= image_tag("#{article.image_url_2}") %>
        <div class="card-trip-infos">
          <div>
            <h2><%= article.title %></h2>
            <h3><%= article.sous_titre %></h3>
            <p><%= article.lieu %></p>
          </div>
          <div class="card-trip-plus">
            <h4 class="card-trip-pricing"><%= article.date %></h4>
            <div class="btn-desk"><%= link_to "En savoir plus", article_path(article.id)%></div>
            <div class="btn-resp"><%= link_to "+", article_path(article.id)%></div>
            </div>
        </div>

    </div>
  <% end %>
</div>

<%= render "components/footer" %>

</div>

app/views/articles/new.html.erb
<div class="d-flex container justify-content-center display-bubble">
    <%= simple_form_for(@article) do |f| %>

         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
          <h3 class="title-new">Ajouter un article</h3>
          <p class="conseil">Essayez de répartir le texte sur les différents champs intitulés "content" pour plus d'harmonie.</p>
           <%= f.input :title %>
           <%= f.input :sous_titre %>
           <%= f.input :date %>
           <%= f.input :lieu %>
           <%= f.input :video %>
           <%= f.input :image_url %>
           <%= f.input :legend %>
           <%= f.input :content %>
           <%= f.input :image_url_2 %>
           <%= f.input :legend_2 %>
           <%= f.input :content_2 %>
           <%= f.input :image_url_3 %>
           <%= f.input :legend_3 %>
           <%= f.input :content_3 %>
           <%= f.input :image_url_4 %>
           <%= f.input :legend_4 %>
           <%= f.input :content_4 %>
           <%= f.input :image_url_5 %>
           <%= f.input :legend_5 %>
           <%= f.input :content_5 %>
           <%= f.input :image_url_6 %>
           <%= f.input :legend_6 %>
           <%= f.input :image_url_7 %>
           <%= f.input :legend_7 %>
           <%= f.input :image_url_8 %>
           <%= f.input :legend_8 %>
           <%= f.input :image_url_9 %>
           <%= f.input :legend_9 %>
           <%= f.input :image_url_10 %>
           <%= f.input :legend_10 %>


         </div>

         <div class="form-actions">
           <%= f.button :submit, class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>
</div>

app/views/articles/show.html.erb
<div class="container-ok">
<%= render "components/header" %>
<body style="background-color:#FF0000;">
  <div class="img-back-blanc"><%= link_to(image_tag("cc.png", alt: "QQ29 - all rights reserved."), articles_path) %></div>
<div class="center-div">
<div class="card-article-show">
<div class="article_info img_article_show">
  <h1 class="feature"><%= @article.title %></h1>
  <h2 class="feature"><%= @article.sous_titre %></h2>
<div class="display-info-article-show">
  <p class="feature"><%= @article.date %></p>
  <p>-</p>
  <p><%= @article.lieu %></p>
</div>
<div class="center-div-2">

  <%= image_tag("#{@article.image_url}") %>
  <h5><%= @article.legend %></h5>
  <p><%= @article.content %></p>
 <% if @article.video != ""  %>
  <iframe width="845" height="560"
    src="<%= @article.video %>"
    frameborder="0"
    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen>
  </iframe>
  <% end %>
  <%= image_tag("#{@article.image_url_2}") %>
  <h5><%= @article.legend_2 %></h5>
  <p><%= @article.content_2 %></p>
  <%= image_tag("#{@article.image_url_3}") %>
  <h5><%= @article.legend_3 %></h5>
  <p><%= @article.content_3 %></p>
  <%= image_tag("#{@article.image_url_4}") %>
  <h5><%= @article.legend_4 %></h5>
  <p><%= @article.content_4 %></p>
  <%= image_tag("#{@article.image_url_5}") %>
  <h5><%= @article.legend_5 %></h5>
  <p><%= @article.content_5 %></p>
  <%= image_tag("#{@article.image_url_6}") %>
  <h5><%= @article.legend_6 %></h5>
  <%= image_tag("#{@article.image_url_7}") %>
  <h5><%= @article.legend_7 %></h5>
  <%= image_tag("#{@article.image_url_8}") %>
  <h5><%= @article.legend_8 %></h5>
  <%= image_tag("#{@article.image_url_9}") %>
  <h5><%= @article.legend_9 %></h5>
  <%= image_tag("#{@article.image_url_10}") %>
  <h5><%= @article.legend_10 %></h5>
</div>
</div>
</div>
</div>

<%= render "components/footer" %>
</body>
</div>

app/views/avatars/edit.html.erb
<div class="container-ok">
  <div class="d-flex container justify-content-center display-bubble">



    <%= simple_form_for(@avatar) do |f| %>
         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
            <h3 class="title-new">Modifier un avatar</h3>
           <%= f.input :nom %>
           <%= f.input :prenom %>
           <%= f.input :role %>
           <%= f.input :bio_url %>
           <%= f.input :img_url %>
           <%= f.select :category_id, Category.all.map {|c| [c.name, c.id]}%>

         </div>

         <div class="form-actions">
           <%= f.submit "Enregistrer", class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>
</div>

app/views/avatars/new.html.erb
<div class="container-ok">
<div class="d-flex container justify-content-center display-bubble">
    <%= simple_form_for(@avatar) do |f| %>

         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
          <h3 class="title-new">Ajouter un avatar</h3>
          <p class="conseil">Essayez de répartir le texte sur les différents champs intitulés "content" pour plus d'harmonie.</p>
           <%= f.input :nom %>
           <%= f.input :prenom %>
           <%= f.input :role %>
           <%= f.input :bio_url %>
           <%= f.input :img_url %>
           <%= f.select :category_id, Category.all.map {|c| [c.name, c.id]}%>
         </div>

         <div class="form-actions">
           <%= f.button :submit, class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>
</div>

app/views/categories/index.html.erb
<div class="container-ok">
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>

        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>
</div>

app/views/categories/new.html.erb
<div class="container-ok">
<div class="d-flex container justify-content-center display-bubble">
    <%= simple_form_for(@category) do |f| %>

         <%= f.error_notification %>
         <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

         <div class="form-inputs">
          <h3 class="title-new">Ajouter une catégorie</h3>
          <p class="conseil">Essayez de répartir le texte sur les différents champs intitulés "content" pour plus d'harmonie.</p>
           <%= f.input :name %>

         </div>

         <div class="form-actions">
           <%= f.button :submit, class: "btn btn-danger title-new" %>
         </div>
       <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Collectif RPZ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="7TnxFjK-xMkNumScoUAwdH-UX7mnRU5cMtWphSvxV54" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-ok">
<%= render "components/header" %>
<div class="banner banner-resp" style="background-image: linear-gradient(122deg, rgba(0,0,0,0.1699054621848739) 0%, rgba(255,255,255,0.3575805322128851) 71%, rgba(0,0,0,0.2819502801120448) 100%), url(https://res.cloudinary.com/dhvdnppdx/image/upload/v1599410504/banni%C3%A8re/leora-dowling-rq5ZYVt4aus-unsplash_myefu4.jpg);">
  <div class="container-banner">
    <%= image_tag("Desktop HD.png", alt: "Quelque chose de neuf")%>
    <a class="btn btn-light btn-banner" href="https://www.helloasso.com/associations/collectif-rpz/formulaires/1/widget">Nous soutenir</a>
  </div>
</div>

  <div class="display-section-1 display-section-1-resp">
    <div class="text-div">
      <h1 class="title-site">Le collectif</h1>
      <p class="paraph-site">Le Collectif RPZ, régi sous statut associatif, se présente comme une plateforme et pépinière culturelle située à Pantin dans un espace industriel de 150m2.

L’association a pour ambition de promouvoir et de valoriser la création artistique contemporaine dans le domaine des arts plastiques.  <br />
 <br />Pour cela, elle s’engage pleinement dans la réalisation de projets culturels en collaboration avec des plasticiens.ennes, associations et représents.es de la culture extérieurs. Elle cherche aussi à promouvoir le travail de ses membres qui exercent dans ce lieu à la fois atelier et espace de présentation.

Le collectif veut concentrer en son sein les énergies et initiatives d’artistes et d’acteurs engagés.es dans la culture, afin de lutter contre une dissémination des moyens et des savoirs.

Elle promeut ainsi une mise en réseau inclusive, ouverte sur l’extérieur. L’association organise tout au long de l’année des échanges et évènements entre artistes, associations et acteurs culturels afin de bâtir et de penser le monde de la culture d’aujourd’hui et de demain.<br />
  <br />

Elle est également un espace d’entraide privilégiant l’accès à des formations techniques pour ses artistes. Ses membres se voient garantis l’accès à une diversité d’outils et d’espaces partagés, ceci pour un montant forfaitaire assez bas qui comprend une part mutualisée.

Le collectif souhaite militer pour l’égalité des chances, des moyens et des accès pour ses artistes résidents, tout en s’engageant dans une dynamique collective ouverte avec volonté sur le maillage de nouvelles rencontres. </div>
    <div class="div-img-section-1">
      <img src="https://res.cloudinary.com/dhvdnppdx/image/upload/v1603141635/Articles/Expo%20bonjour/Richard/rpznew_pdqg67.png" class="img-section-1 img-section-1-resp">
      <p class="credit-home">Crédit photo - RPZ</p>
    </div>
  </div>

  <div class="display-section-2 display-section-2-resp">
    <div class="sous-section-1">
      <%= image_tag("museum.png", alt: "Edit Entry")%>
      <h1 class="title-section-2C">Collectif d'artistes</h1>
    </div>
    <div class="sous-section-1">
      <%= image_tag("settings.png", alt: "Edit Entry")%>
      <h1 class="title-section-2B">Mutualisation des moyens et des savoirs</h1>
    </div>
    <div class="sous-section-1">
      <%= image_tag("marketing.png", alt: "Edit Entry")%>
      <h1 class="title-section-2">Évènements toute l'année !</h1>
    </div>
  </div>

<%= render "components/footer" %>
</div>

app/views/pages/mentions.html.erb
<div class="container-ok">
<%= render "components/header" %>
<body style="background-color:#FF0000;">
<div class="img-back-blanc"><%= link_to(image_tag("cc.png", alt: "QQ29 - all rights reserved."), root_path) %></div>

  <div class="container-ml mentions-legales">
    <h1>MENTION LÉGALES</h1>
    <p>Le présent site http://www.collectifrpz.com est édité par :</p>
    <p>RPZ, Association loi 1901, dont le siège social est situé au 22 rue marmontel, 75015 Paris</p>
    <p>RNA : W931021958</p>
    <p>Adresse email : collectif.rpz@gmail.com</p>
    <p>Hébergeur du site : Namecheap, Phoenix, Arizona, United States</p>
    <p>Responsable du site : Madame Camille Sauer</p>
    <p>Collectif RPZ - Tous droits réservés.</p>
  </div>
<%= render "components/footer" %>
</body>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>